### ISSUE TITLE
Latest Otel configuration is failing

### ISSUE THREAD

**Issue by rgildein** [canonical/knative-operators#231]
### Bug Description

The latest version  (0.111.0) of otel collector require change in the manifest, specifically in the [exporters](https://github.com/canonical/knative-operators/blob/167dea78d6d7d8013d8294f33a68c1c4d55c54a1/charms/knative-operator/src/manifests/observability/collector.yaml.j2#L12-L15).

I checked the [change log for 0.111.0 version](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md#v01110), but I didn't see anything particular. I know that the changes are in latest version, because I tried to test 0.110.0 and cos integration test pass without issue.

### To Reproduce

1. tox -vve cos-integration -- --model cos-test

### Environment

Juju 3.5.4-genericlinux-amd64 
MicroK8s v1.30.5 revision 7235 

### Relevant Log Output

```shell
$ k logs pod/otel-collector-6476c498f5-7sb8n -n cos-test
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': the logging exporter has been deprecated, use the debug exporter instead
2024/10/09 19:49:16 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': the logging exporter has been deprecated, use the debug exporter instead
```

**Comment by orfeas-k** [comment]
Quick comment that it could be the line "logging" since I see in the new release https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.111.0:
* https://github.com/open-telemetry/opentelemetry-collector-releases/commit/545bd7c1dd76f950f0f3dfcc04218732afdbdb5e Remove the deprecated logging exporter (https://github.com/open-telemetry/opentelemetry-collector-releases/pull/682)

Looking at linked issue and PRs, I see this https://github.com/open-telemetry/opentelemetry-operator/pull/3259/files.

**Comment by orfeas-k** [comment]
Looks like removing the `logging` from the collector from the manifest file [worked](https://github.com/canonical/knative-operators/pull/230/commits/1c8a848c8e57ac53005e624147b354a1de571a20)
