### ISSUE TITLE
KNative is installed outside of the model namespace

### ISSUE THREAD

**Issue by Barteus** [canonical/knative-operators#63]
When KNative is deployed some components are deployed in the namespaces outside the model namespace like knative-serving or knative-eventing.

**Comment by DomFleischmann** [comment]
This is the expected behaviour, KNative Serving and Eventing need to be deployed in different namespaces, therefore it was chosen for it to be deployed this way.  This is clearly documented in the README ( see where section [here](https://github.com/canonical/knative-operators#knative-serving)). It can also be configured with the `namespace` juju config variable.
